services:
  db:
    image: postgres:13 
    container_name: stylecraft_ai_db
    restart: always
    environment:
      POSTGRES_USER: stylecraftuser      
      POSTGRES_PASSWORD: stylecraftpassword  
      POSTGRES_DB: stylecraft_interactions_db 
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data_stylecraft:/var/lib/postgresql/data 

volumes:
  postgres_data_stylecraft:  
